paths:
  source_sensor_data_directory: "/path/to/ingolstadt"
  source_bus_signals_filepath: "/path/to/ingolstadt/bus/20190401145936_bus_signals.json"
  source_sensor_configuration_filepath: "/path/to/ingolstadt/cams_lidars.json"

  target_directory: "/path/to/ingolstadt_output"

filter:
  #start_timestamp: 1533906480
  stop_timestamp: 1554121568
